### ISSUE TITLE
cannot install with pip

### ISSUE THREAD

**Issue by mihai-satmarean** [kulinacs/ansiqa#2]
Looking for an alternate to ansigenome, your project looks interesting.
maybe I can get some help on the following error?

`cat /etc/redhat-release
CentOS Linux release 7.6.1810 (Core)`

`pip install ansiqa
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
Collecting ansiqa
  Using cached https://files.pythonhosted.org/packages/e0/1e/2e3cedd754e71e2c853c1da0a07a45b1a20cd6514f6125b904424b2ddfd6/ansiqa-0.2.1.tar.gz
    ERROR: Complete output from command python setup.py egg_info:
    ERROR: Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-XIN5wX/ansiqa/setup.py", line 10, in <module>
        with open(path.join(here, 'README.md'), encoding='utf-8') as f:
      File "/usr/lib64/python2.7/codecs.py", line 881, in open
        file = __builtin__.open(filename, mode, buffering)
    IOError: [Errno 2] No such file or directory: '/tmp/pip-install-XIN5wX/ansiqa/README.md'
    ----------------------------------------
ERROR: Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-XIN5wX/ansiqa/`

Thanks!

**Comment by mihai-satmarean** [comment]
got it running , needed :
yum install 'graphviz-devel.x86_64'
pip install libcgraph

**Comment by mihai-satmarean** [comment]
after I got it running I get this:
`ansiqa --help
Traceback (most recent call last):
  File "/usr/bin/ansiqa", line 11, in <module>
    load_entry_point('ansiqa==0.2.1', 'console_scripts', 'ansiqa')()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2843, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2434, in load
    return self.resolve()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2440, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python2.7/site-packages/ansiqa-0.2.1-py2.7.egg/ansiqa/__init__.py", line 80
    indent=4, block_seq_indent=2), end='')
                                      ^
SyntaxError: invalid syntax`

**Comment by kulinacs** [comment]
probably an issue with updated Python versions. I haven't worked on this in a couple of years. I'll take a look and see if I can get it working with current Python versions, but you should note this project is considered dead by me and you might consider forking it if you want active development.

**Comment by kulinacs** [comment]
Looks like the old version of Ruamel.yaml being used has an issue with the latest version of Python, and the breaking API change means newer versions likely won't work without changes. PRs welcome, but I do not intend to fix this.

**Comment by mihai-satmarean** [comment]
Hi, thanks for looking into it, 
I am not a developer that can fix this.
Since this is a very useful idea, maybe would be a good idea to offer the project for adoption :)
